Repository versatus/lasr, pull requests merged in 2024-04, with the labels that each got.

#81 Add format CI check to workflow
  .github/workflows/rust.yml
  Cargo.toml
  crates/actors/Cargo.toml
  crates/cli/Cargo.toml
  crates/clients/Cargo.toml
  crates/compute/Cargo.toml
  crates/messages/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/main.rs
  crates/rpc/Cargo.toml
  crates/types/Cargo.toml
  crates/wallet/Cargo.toml
  infra/foundry/fly.toml
  infra/ipfs/fly.toml
Labels: CI

#83 Add `future_pool` to `Batcher`
  Cargo.lock
  crates/actors/Cargo.toml
  crates/actors/src/batcher.rs
  crates/node/Cargo.toml
  crates/node/src/main.rs
Labels: enhancement

#104 Change hard-coded thread count to `num_cpus::get()`
  crates/actors/Cargo.toml
  crates/actors/src/validator.rs
Labels: bug

#103 Add `ActorExt` & `Batcher::handle_transaction_error`
  Cargo.lock
  crates/actors/src/batcher.rs
  crates/actors/src/helpers.rs
  crates/node/Cargo.toml
  crates/node/src/main.rs
Labels: documentation, enhancement

#110 Fix workspace clippy warnings
  crates/actors/src/batcher.rs
  crates/actors/src/helpers.rs
  crates/actors/src/rpc_server.rs
  crates/cli/src/cli.rs
  crates/messages/src/messages.rs
  crates/types/src/account.rs
  crates/types/src/programming_model.rs
  crates/types/src/signing.rs
  crates/types/src/token.rs
  crates/types/src/transaction.rs
  crates/wallet/src/wallet.rs
Labels: code quality

#133 Make actor `JoinHandle`s persist the life of the program, add log for `GetNextBatch`
  crates/actors/src/batcher.rs
  crates/node/src/main.rs
Labels: bug

#138 Add hex string value parsing to `U256Wrapper` `FromStr` implementation
  crates/cli/src/cli.rs
Labels: enhancement

#131 Add `Executor` actor to future handler thread pool
  Cargo.lock
  crates/actors/src/batcher.rs
  crates/actors/src/executor.rs
  crates/actors/src/helpers.rs
  crates/node/Cargo.toml
  crates/node/src/main.rs
Labels: enhancement
