Repository versatus/lasr, pull requests merged in 2024-07, with the labels that each got.

#233 Add helpful error message to account `put` method
  crates/actors/src/batcher.rs
Labels: bug

#230 Rework `remote` & `local` features
  crates/actors/Cargo.toml
  crates/actors/src/engine.rs
  crates/actors/src/executor.rs
  crates/cli/Cargo.toml
  crates/compute/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/main.rs
Labels: code quality

#235 Add cargo build check to CI
  .github/workflows/rust.yml
Labels: CI

#234 Remove unused files
  .github/workflows/release-lasr-cli.yml
  .github/workflows/release-lasr-cross.yml
  .github/workflows/release-via-nix.yml
  .taskfiles/setup/tasks.yaml
  Dockerfile
  Taskfile.yaml
  docker-compose.yml
  entrypoints/pd.sh
  entrypoints/tikv.sh
  shell.nix
  stack.yml
Labels: code quality

#239 Add error handling to OciManager
  Cargo.lock
  crates/actors/src/batcher.rs
  crates/compute/src/compute.rs
Labels: code quality

#241 Update `EigenDaGrpcClient`, add optional env var for server address
  Cargo.lock
  README.md
  crates/node/.env-sample
  crates/node/src/environment.rs
  crates/node/src/main.rs
Labels: enhancement

#243 Perform `OciBundler` checks after building
  crates/actors/src/executor.rs
  crates/compute/src/compute.rs
  crates/node/src/main.rs
Labels: bug

#246 Add environment variable for `runsc` binary path
  README.md
  crates/actors/src/executor.rs
  crates/compute/src/compute.rs
  crates/node/.env-sample
  crates/node/src/environment.rs
  crates/node/src/main.rs
Labels: bug

#249 Add `grpcurl` binary path environment variable
  Cargo.lock
  README.md
  crates/node/.env-sample
  crates/node/src/environment.rs
  crates/node/src/main.rs
Labels: enhancement

#250 Use runsc runtime path in `OciManager::run_container`
  crates/compute/src/compute.rs
Labels: bug

#251 Add `flake.nix`
  .gitignore
  Cargo.lock
  README.md
  crates/actors/Cargo.toml
  crates/cli/Cargo.toml
  crates/cli/README.md
  crates/compute/Cargo.toml
  crates/contract/Cargo.toml
  crates/eo_listener/Cargo.toml
  crates/messages/Cargo.toml
  crates/node/Cargo.toml
  crates/node/README.md
  crates/rpc/Cargo.toml
  crates/types/Cargo.toml
  crates/wallet/Cargo.toml
  deny.toml
  flake.lock
  flake.nix
  nixos/modules/deployments/README.md
  nixos/modules/deployments/common/default.nix
  nixos/modules/deployments/debug/debug-options.nix
  nixos/modules/deployments/prod/prod-options.nix
  nixos/overlay.nix
Labels: enhancement

#252 Add GitHub codespace devcontainer
  .devcontainer/devcontainer.json
  .envrc.recommended
Labels: feature

#253 Update `flake.lock`
  flake.lock
Labels: maintenance

#257 Exclude `persistence.rs` from `lasr_types` crate
  crates/types/Cargo.toml
Labels: publishing

#258 Remove `persistence.rs` exclusion
  crates/types/Cargo.toml
Labels: publishing
