Repository versatus/lasr, pull requests merged in 2024-06, with the labels that each got.

#201 Delete crates/cli/src/main.rs
  crates/cli/src/main.rs
Labels: code quality

#208 Reacquire `EoServerActor` after `ActorStatus::Stopped` in `EoServerActor::run()`
  crates/actors/src/eo_server.rs
Labels: bug

#186 Add E2E `account_type: Program()` example to `tikv_example`
  crates/node/examples/tikv_account_example.rs
Labels: documentation

#211 Tracing migration
  Cargo.lock
  crates/actors/Cargo.toml
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/blob_cache.rs
  crates/actors/src/da_client.rs
  crates/actors/src/engine.rs
  crates/actors/src/eo_client.rs
  crates/actors/src/eo_server.rs
  crates/actors/src/executor.rs
  crates/actors/src/helpers.rs
  crates/actors/src/pending_transactions.rs
  crates/actors/src/rpc_server.rs
  crates/actors/src/scheduler.rs
  crates/actors/src/validator.rs
  crates/compute/Cargo.toml
  crates/compute/src/compute.rs
  crates/node/Cargo.toml
  crates/node/src/main.rs
  crates/types/Cargo.toml
  crates/types/src/account.rs
  crates/types/src/signing.rs
  crates/types/src/token.rs
  crates/types/src/transaction.rs
  crates/wallet/Cargo.toml
  crates/wallet/src/wallet.rs
Labels: bug

#214 Filter `blocks_processed` for `EoServer` on setup
  Cargo.lock
  crates/actors/src/eo_server.rs
  crates/node/src/main.rs
Labels: bug

#219 Removed TokenFieldValue::Balance & TokenFieldValue::TokenIds from token.rs
  crates/actors/src/validator.rs
  crates/types/src/token.rs
Labels: code quality

#210 Add testing framework for events that update `Account`
  .github/workflows/rust.yml
  Cargo.lock
  crates/actors/Cargo.toml
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/eo_server.rs
  crates/actors/src/manager.rs
  crates/actors/tests/account.rs
  crates/messages/Cargo.toml
  crates/messages/src/messages.rs
  crates/node/Cargo.toml
  crates/node/src/main.rs
  crates/types/Cargo.toml
  crates/types/src/account.rs
  crates/types/src/lib.rs
  crates/types/src/persistence.rs
  crates/types/src/programming_model.rs
  crates/types/src/token.rs
  crates/types/src/transaction.rs
Labels: enhancement, feature

#200 Check all env vars for existence on startup; Add .env-sample
  Cargo.lock
  README.md
  crates/node/.env-sample
  crates/node/Cargo.toml
  crates/node/src/environment.rs
  crates/node/src/main.rs
Labels: documentation, code quality

#99 Add clippy CI check to workflow
  .github/workflows/rust.yml
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/da_client.rs
  crates/actors/src/engine.rs
  crates/actors/src/eo_client.rs
  crates/actors/src/eo_server.rs
  crates/actors/src/executor.rs
  crates/actors/src/helpers.rs
  crates/actors/src/pending_transactions.rs
  crates/actors/src/scheduler.rs
  crates/actors/src/validator.rs
  crates/actors/tests/account.rs
  crates/cli/src/cli.rs
  crates/messages/src/actor_types.rs
  crates/types/src/account.rs
  crates/types/src/token.rs
  crates/types/src/transaction.rs
Labels: CI

#199 [CHORE] Clean up dependencies
  Cargo.lock
  crates/actors/Cargo.toml
  crates/cli/Cargo.toml
  crates/compute/Cargo.toml
  crates/messages/Cargo.toml
  crates/node/Cargo.toml
  crates/types/Cargo.toml
  crates/wallet/Cargo.toml
Labels: code quality

#206 Fix `token` overwrites in `BridgeIn` events
  crates/actors/src/batcher.rs
  crates/actors/src/pending_transactions.rs
  crates/actors/src/validator.rs
  crates/types/src/account.rs
Labels: bug

#223 Timeout IPFS Calls
  crates/actors/src/eo_server.rs
  crates/compute/src/compute.rs
Labels: enhancement

#225 Move `eo_listener` repo into workspace
  Cargo.lock
  Cargo.toml
  crates/actors/Cargo.toml
  crates/eo_listener/Cargo.toml
  crates/eo_listener/eo_contract_abi.json
  crates/eo_listener/src/lib.rs
  crates/eo_listener/src/main.rs
  crates/messages/Cargo.toml
  crates/node/Cargo.toml
Labels: code quality

#229 FIX: `eo_contract_abi.json` not found on start-up
  crates/eo_listener/src/eo_contract_abi.rs
  crates/eo_listener/src/lib.rs
  crates/eo_listener/src/main.rs
  crates/node/src/main.rs
Labels: bug
