Repository versatus/lasr, pull requests merged in 2024-05, with the labels that each got.

#140 Add `ValidatorActor` to future handler
  crates/actors/src/validator.rs
  crates/node/src/main.rs
Labels: enhancement

#141 Add `DaClientActor` to future handler
  crates/actors/src/da_client.rs
  crates/node/src/main.rs
Labels: enhancement

#142 Add `EngineActor` to future handler
  crates/actors/src/engine.rs
  crates/node/src/main.rs
Labels: enhancement

#143 Remove unnecessary async await points in `EoServerActor`
  crates/actors/src/eo_server.rs
  crates/node/src/main.rs
Labels: code quality

#144 Remove unnecessary async await points from `LasrRpcServerActor`
  crates/actors/src/rpc_server.rs
Labels: code quality

#145 Add `EoClientActor` to future handler
  Cargo.lock
  crates/clients/Cargo.toml
  crates/clients/src/eo_client.rs
  crates/node/src/main.rs
Labels: enhancement

#147 Handle unwrap for `DaClient` actor
  crates/actors/src/da_client.rs
Labels: bug

#148 Add `batch_header_hash` and `blob_index` to error log in `retrieve_account`
  crates/actors/src/da_client.rs
Labels: code quality

#150 Add more robust error handling to `Actor` methods
  Cargo.lock
  Cargo.toml
  crates/actors/Cargo.toml
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/da_client.rs
  crates/actors/src/engine.rs
  crates/actors/src/eo_client.rs
  crates/actors/src/helpers.rs
  crates/actors/src/lib.rs
  crates/actors/src/pending_transactions.rs
  crates/actors/src/scheduler.rs
  crates/actors/src/validator.rs
  crates/clients/Cargo.toml
  crates/clients/src/lib.rs
  crates/node/Cargo.toml
  crates/node/src/main.rs
Labels: code quality

#156 Add extra logs for `eo_server::run`
  crates/actors/src/eo_server.rs
Labels: bug

#157 Fix eo filter bug
  crates/actors/src/eo_server.rs
  crates/node/src/main.rs
  entrypoints/pd.sh
  entrypoints/tikv.sh
  stack.yml
Labels: bug

#153 Add `ActorManager` and actor supervisors for each actor
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/blob_cache.rs
  crates/actors/src/da_client.rs
  crates/actors/src/engine.rs
  crates/actors/src/eo_client.rs
  crates/actors/src/eo_server.rs
  crates/actors/src/executor.rs
  crates/actors/src/helpers.rs
  crates/actors/src/lib.rs
  crates/actors/src/manager.rs
  crates/actors/src/pending_transactions.rs
  crates/actors/src/rpc_server.rs
  crates/actors/src/scheduler.rs
  crates/actors/src/validator.rs
  crates/messages/src/actor_types.rs
  crates/node/src/main.rs
Labels: feature

#155 Add write hooks for persistence layer
  Cargo.lock
  crates/actors/Cargo.toml
  crates/actors/src/batcher.rs
  crates/node/Cargo.toml
  crates/node/examples/tikv_account_example.rs
Labels: feature

#166 Make handle next batch request blocking
  crates/actors/src/batcher.rs
  crates/actors/src/da_client.rs
Labels: bug

#167 Fix TIKV batcher logs, log account map from batcher
  crates/actors/src/batcher.rs
Labels: bug

#168 Use for loop, remove while let next
  crates/actors/src/batcher.rs
Labels: bug

#164 Remove time constraint for acquiring blob index from EO
  crates/actors/src/helpers.rs
Labels: bug

#170 Add read hooks for persistence layer
  Cargo.lock
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/manager.rs
  crates/messages/Cargo.toml
  crates/messages/src/messages.rs
  crates/node/src/main.rs
Labels: feature

#173 Remove timeout requirement for acquiring account from DA
  crates/actors/src/helpers.rs
Labels: code quality

#174 Add a 15s interval between `EoServer` block reads
  crates/actors/src/eo_server.rs
Labels: bug

#175 Add better logging for `ProcessGroupChanged` supervision event
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/blob_cache.rs
  crates/actors/src/da_client.rs
  crates/actors/src/engine.rs
  crates/actors/src/eo_client.rs
  crates/actors/src/eo_server.rs
  crates/actors/src/executor.rs
  crates/actors/src/helpers.rs
  crates/actors/src/pending_transactions.rs
  crates/actors/src/rpc_server.rs
  crates/actors/src/scheduler.rs
  crates/actors/src/validator.rs
Labels: code quality

#177 Update `get_account()` method in `helpers.rs`
  crates/actors/src/helpers.rs
Labels: enhancement

#180 Remove calls to get `Account` from DA & EO
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/engine.rs
  crates/actors/src/eo_client.rs
  crates/actors/src/helpers.rs
  crates/actors/src/scheduler.rs
  crates/actors/src/validator.rs
  crates/messages/src/messages.rs
  crates/node/examples/tikv_account_example.rs
Labels: bug, code quality

#188 Use full hex String for persistence reads, add more robust logging
  crates/actors/src/account_cache.rs
  crates/actors/src/batcher.rs
  crates/actors/src/engine.rs
  crates/actors/src/executor.rs
  crates/actors/src/helpers.rs
  crates/actors/src/scheduler.rs
  crates/actors/src/validator.rs
  crates/messages/src/messages.rs
  crates/node/src/main.rs
  crates/types/src/account.rs
Labels: bug, code quality

#178 Add README.md for TiKV persistence store
  crates/node/examples/README.md
  scripts/pd-server.sh
  scripts/tikv-server.sh
Labels: documentation

#195 Bump `jsonrpsee` version & Server connection limit
  Cargo.lock
  crates/actors/Cargo.toml
  crates/actors/src/engine.rs
  crates/actors/src/eo_server.rs
  crates/actors/src/helpers.rs
  crates/actors/src/rpc_server.rs
  crates/actors/src/scheduler.rs
  crates/cli/Cargo.toml
  crates/messages/Cargo.toml
  crates/node/Cargo.toml
  crates/node/src/main.rs
  crates/rpc/Cargo.toml
  crates/rpc/src/rpc.rs
Labels: bug

#197 Validator refactor from investigating #194
  Cargo.lock
  crates/actors/src/validator.rs
  crates/types/src/programming_model.rs
Labels: code quality

#187 Read container output from temp file instead of Std Out
  crates/compute/src/compute.rs
Labels: bug
